from django.db import models
from django.contrib import admin
# Create your models here.
class ServerManger(models.Model):
    agent = models.CharField(max_length=1024,blank=True)
    zone = models.IntegerField(blank=True)
    ip = models.CharField(max_length=1024,blank=True,default=True)
    addtime = models.CharField(max_length=100,blank=True)
    wwwdir = models.CharField(max_length=1024,blank=True)
    javadir = models.CharField(max_length=1024,blank=True)
    gamedbname = models.CharField(max_length=128,blank=True)
    gamedbip = models.CharField(max_length=128,blank=True)
    gamedbport = models.CharField(max_length=128,blank=True)
    gamedatadbname = models.CharField(max_length=128,blank=True)
    gamedatadbip = models.CharField(max_length=128,blank=True)
    gamedatadbport = models.CharField(max_length=128,blank=True)
    gamelogdbname = models.CharField(max_length=128,blank=True)
    gamelogdbip = models.CharField(max_length=128,blank=True)
    gamelogdbport = models.CharField(max_length=128,blank=True)
    gateminaserverport = models.CharField(max_length=128,blank=True)
    gateminaserversslport = models.CharField(max_length=128,blank=True)
    gateinnerserverport = models.CharField(max_length=128,blank=True)
    worldinnerserverport = models.CharField(max_length=128,blank=True)
    worldhttpserverport = models.CharField(max_length=128,blank=True)
    openservertime = models.CharField(max_length=128,blank=True)
    GVER = models.CharField(max_length=128,blank=True)
    RESVER = models.CharField(max_length=128,blank=True)
    STRESVER = models.CharField(max_length=128,blank=True)
    java_version = models.CharField(max_length=1024,blank=True)
    sum_zone = models.IntegerField(blank=True)
    kaifu_config = models.CharField(max_length=10,blank=True)
    lianfuid = models.CharField(max_length=128,blank=True)
    check_kaifutime = models.CharField(max_length=10,blank=True)
    isdelete = models.IntegerField(blank=True)
    hequserverid = models.IntegerField(blank=True)
    hequtime = models.CharField(max_length=40,blank=True)
    BOOTVER = models.CharField(max_length=128,blank=True)
    DATAVER = models.CharField(max_length=128,blank=True)
    def __unicode__(self):
        return self.agent
class login(models.Model):
    username = models.CharField(max_length=30)
    password = models.CharField(max_length=30)
admin.site.register(login)